added workflow file for automatic release with github actions
Team-MostWanted/galera-health pull request #1
Opened 2022-08-02 11:12 UTC by Lveltmaat

2022-08-02 11:13 UTC, Lveltmaat commented
Het scriptje checkt niet of het bestandje versions bestaat of niet

2022-08-08 07:34 UTC, rtuk requested changes

2022-08-08 07:34 UTC, rtuk commented on .github/workflows/action.yml
> +      uses: actions/create-release@v1
This action is archived and no longer maintained

2022-08-08 07:34 UTC, rtuk commented on .github/workflows/action.yml
> +
remove unneeded empty lines (1 final new line is sufficient)

2022-08-08 07:34 UTC, rtuk commented on .github/workflows/action.yml
> +
Remove .travis.yml

2022-08-08 07:34 UTC, rtuk commented on .github/workflows/action.yml
> +
remove tags used for testing

2022-08-08 07:34 UTC, rtuk commented on .github/workflows/action.yml
> +
remove release (the first release should happen once this PR is merged)

2022-08-08 09:33 UTC, rtuk approved these changes

2022-08-08 13:07 UTC, closed without merging